name: Build Docker Image and Push to ECR

########################################
# Required secrets: 
# - GHA_ROLE_ARN 
########################################

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  REPOSITORY: testing #enter the respository name

permissions:
 id-token: write
 contents: read

jobs:
  build-and-deploy-image:
    name: Build and Deploy to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 8

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.GHA_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$COMMIT_SHA -t $REGISTRY/$REPOSITORY:latest .
        docker image push --all-tags $REGISTRY/$REPOSITORY
