name: Build Docker Image and Push to ECR

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
    secrets:
      role-to-assume:
        required: true

permissions:
 id-token: write
 contents: read

jobs:
  build-and-deploy-image:
    name: Build and Deploy to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 8

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag docker image with short commit SHA
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ github.event.repository.name }}
        COMMIT_SHA: ${{ steps.short-sha.outputs.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$COMMIT_SHA .
      shell: bash

    - name: Tag docker image with develop
      if: ${{ github.ref_name == 'main' }}
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ github.event.repository.name }}
      run: |
        docker tag $REGISTRY/$REPOSITORY:$COMMIT_SHA $REGISTRY/$REPOSITORY:develop
      shell: bash

    - name: Tag docker image with latest
      if: ${{ github.ref_name == 'production' }}
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ github.event.repository.name }}
      run: |
        docker tag $REGISTRY/$REPOSITORY:$COMMIT_SHA $REGISTRY/$REPOSITORY:latest
      shell: bash
  
    - name: Push docker image tags to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ github.event.repository.name }}
      run: |
        docker image push --all-tags $REGISTRY/$REPOSITORY
      shell: bash